apiVersion: batch/v1
kind: Job
metadata:
  name: grpc-go-client
spec:
  template:
    metadata:
      labels:
        app: grpc-go-client
    spec:
      restartPolicy: Never
      containers:
        - name: grpc-go-client
          image: grpc-client:local
          imagePullPolicy: IfNotPresent
          args: ["-host", "grpc-go-server-svc:5050"]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
  backoffLimit: 3
