version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy/http
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy/grpc/docker/client
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy/grpc/docker/server
    schedule:
      interval: weekly
