apiVersion: v1
kind: Service
metadata:
  name: grpc-go-server-svc
  labels:
    app: grpc-go-server-svc
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app: grpc-go-server